CREATE TABLE CUSTOMERS (
    CUSTOMER_ID  int AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;